Update diabetes_regression-ci.yml for Azure Pipelines

diff --git a/.pipelines/diabetes_regression-ci.yml b/.pipelines/diabetes_regression-ci.yml
--- a/.pipelines/diabetes_regression-ci.yml
+++ b/.pipelines/diabetes_regression-ci.yml
@@ -34,23 +34,18 @@ stages:
     container: mlops
     timeoutInMinutes: 0
     steps:
-    - task: Docker@2
-      inputs:
-          command: 'buildAndPush'
-          Dockerfile: '**/Dockerfile'
-
-    - template: code-quality-template.yml
-    - task: AzureCLI@1
-      inputs:
-        azureSubscription: '$(WORKSPACE_SVC_CONNECTION)'
-        scriptLocation: inlineScript
-        workingDirectory: $(Build.SourcesDirectory)
-        inlineScript: |
-          set -e # fail on error
-          export SUBSCRIPTION_ID=$(az account show --query id -o tsv)
-          # Invoke the Python building and publishing a training pipeline
-          python -m ml_service.pipelines.diabetes_regression_build_train_pipeline
-      displayName: 'Publish Azure Machine Learning Pipeline'
+      - template: code-quality-template.yml
+      - task: AzureCLI@1
+        inputs:
+          azureSubscription: '$(WORKSPACE_SVC_CONNECTION)'
+          scriptLocation: inlineScript
+          workingDirectory: $(Build.SourcesDirectory)
+          inlineScript: |
+            set -e # fail on error
+            export SUBSCRIPTION_ID=$(az account show --query id -o tsv)
+            # Invoke the Python building and publishing a training pipeline
+            python -m ml_service.pipelines.diabetes_regression_build_train_pipeline
+        displayName: 'Publish Azure Machine Learning Pipeline'
 
 - stage: 'Trigger_AML_Pipeline'
   displayName: 'Train and evaluate model'
